import NavBar from "@/components/navbar";
import "./globals.css";
import { Suspense } from "react";
import { fetchUser } from "@/lib/fetchUser";
import Link from "next/link";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const userPromise = fetchUser();
  return (
    <html lang="en">
      <body>
        <Link href="/">Back</Link>
        <Suspense fallback={<h1>Loading navigation...</h1>}>
          <NavBar userPromise={userPromise} />
        </Suspense>

        {children}
      </body>
    </html>
  );
}
